const categories = [
    {
        key: 54215742,
        title: "All Products",
        imgUrl: "./src/assets/1.png",
        link: "all",
    },
    {
        key: 54215743,
        title: "Keyboard",
        imgUrl: "./src/assets/2.png",
        link: "keyboard",
    },
    {
        key: 54215744,
        title: "Mouse",
        imgUrl: "./src/assets/3.png",
        link: "mouse",
    },
    {
        key: 54215745,
        title: "Microphone",
        imgUrl: "./src/assets/4.png",
        link: "microphone",
    },
    {
        key: 54215746,
        title: "Switch",
        imgUrl: "./src/assets/1.png",
        link: "switch",
    },
    {
        key: 54215747,
        title: "Display",
        imgUrl: "./src/assets/2.png",
        link: "display",
    },
    {
        key: 54215748,
        title: "Display",
        imgUrl: "./src/assets/2.png",
        link: "display",
    },
]

const products = [
    {
        id: 12354876546,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Keyboard",
        desc: "This is a modern keyboard",
        price: 69,
    },
    {
        id: 123548765461,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Keyboard",
        desc: "This is a modern keyboard",
        price: 69,
    },
    {
        id: 123548765426,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Mouse",
        desc: "This is a modern keyboard",
        price: 69,
    },
    {
        id: 123548765463,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Keyboard",
        desc: "This is a modern keyboard",
        price: 69,
    },
    {
        id: 123548765464,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Keyboard",
        desc: "This is a modern keyboard",
        price: 69,
    },
    {
        id: 123548765465,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Keyboard",
        desc: "This is a modern keyboard",
        price: 69,
    },
    {
        id: 123548765466,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Keyboard",
        desc: "This is a modern keyboard",
        price: 69,
    },
    {
        id: 123548765467,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Keyboard",
        desc: "This is a modern keyboard",
        price: 69,
    },
    {
        id: 123548765468,
        imgUrl: './src/assets/1.png',
        title: "Keyboard K2 Wireless Mechanical",
        type: "Keyboard",
        desc: "This is a modern keyboard",
        price: 69,
    },
]

export { categories, products };